package com.innovzen.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HISTORY.
 */
public class History {

	private Long id;
	private Long date;
	private Integer inhale;
	private Integer holdInhale;
	private Integer exhale;
	private Integer holdExhale;
	private Long duration;

	public History() {
	}

	public History(Long id) {
		this.id = id;
	}

	public History(Long id, Long date, Integer inhale, Integer holdInhale, Integer exhale, Integer holdExhale, Long duration) {
		this.id = id;
		this.date = date;
		this.inhale = inhale;
		this.holdInhale = holdInhale;
		this.exhale = exhale;
		this.holdExhale = holdExhale;
		this.duration = duration;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDate() {
		return date;
	}

	public void setDate(Long date) {
		this.date = date;
	}

	public Integer getInhale() {
		return inhale;
	}

	public void setInhale(Integer inhale) {
		this.inhale = inhale;
	}

	public Integer getHoldInhale() {
		return holdInhale;
	}

	public void setHoldInhale(Integer holdInhale) {
		this.holdInhale = holdInhale;
	}

	public Integer getExhale() {
		return exhale;
	}

	public void setExhale(Integer exhale) {
		this.exhale = exhale;
	}

	public Integer getHoldExhale() {
		return holdExhale;
	}

	public void setHoldExhale(Integer holdExhale) {
		this.holdExhale = holdExhale;
	}

	public Long getDuration() {
		return duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	@Override
	public String toString() {
		return "History [id=" + id + ", date=" + date + ", inhale=" + inhale + ", holdInhale=" + holdInhale + ", exhale=" + exhale + ", holdExhale=" + holdExhale + ", duration=" + duration + "]";
	}

}
